### PR TITLE
Add docs from gen-markdown

### PR DESCRIPTION
**Pull request by ml-evs**
Not sure if we want to commit this to the repo or dynamically generate/serve on gh pages, can decide soon.

### CODE REVIEW

**Comment by PeterKraus** [comment]
Those are all automatically generated from the descriptions in the schema, correct? Then, I'd probably do a GH action that generates them on every push-to-master along with docs.

**Comment by PeterKraus** [comment]
It's not clear to me which part of the `md` files are hand-written and which part is auto-generated. In some instances, the `URI` is not in the `yaml` files but appears in the markdown. I am generally against commiting auto-generated documentation into the repo, and would rather have it (re)built using a GH action on every push-to-master.

**Comment by ml-evs** [comment]
> It's not clear to me which part of the `md` files are hand-written and which part is auto-generated. In some instances, the `URI` is not in the `yaml` files but appears in the markdown. I am generally against commiting auto-generated documentation into the repo, and would rather have it (re)built using a GH action on every push-to-master.

It's all autogenerated, and yeah, it should be hosted rather than committed. I'll convert this PR into generation+push to pages at a later date.

**Comment by ml-evs** [comment]
Delaying until we can add this generation to the CI directly

**Pull request closed without merging**
